name: Lint Commit Messages
on: [pull_request, push]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
