name: Friend Circle

on:
  schedule:
    # Update friend circle automatically everyday at 00:00 UTC
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    paths:
      - "links"
      - "template.html"
      - "public/*"

jobs:
  friend_circle:
    name: Friend Circle
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Friend Circle
      uses: mumu-lhl/simple-friend-circle@main

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: public
        clean: true
        single-commit: true
